# I. Numpy

### Импортируйте NumPy

In [2]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [4]:
array_1 = np.zeros(10)
array_1[4] = 1
array_2 = array_1.reshape(2, 5)
array_2

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [5]:
array_12 = np.arange(10, 50)
array_21 = np.flip(array_12)
even_el = array_21[array_21 % 2 == 0]
print("Одномерный массив:", array_12)
print("Развернутый массив:", array_21)
print("Четные элементы:", even_el)

Одномерный массив: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Развернутый массив: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Четные элементы: [48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [6]:
array_2 = np.arange(9).reshape(3, 3)
array_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [7]:
array_3 = np.random.rand(4, 3, 2)
min_el = np.min(array_3)
max_el = np.max(array_3)
print("Минимум:", min_el, "Максимум:", max_el)

Минимум: 0.006422769131234296 Максимум: 0.9686119602904845


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [8]:
array_21 = np.random.rand(6, 4)
array_22 = np.random.rand(4, 3)
arr_prois = np.dot(array_21, array_22)
arr_prois

array([[1.36620941, 0.58049447, 1.25259392],
       [1.10210719, 0.74447023, 1.49347828],
       [0.63035968, 0.27575364, 1.09027347],
       [1.73194505, 0.92285408, 1.45765479],
       [1.34528862, 0.57142986, 1.88915834],
       [0.84380665, 0.29341489, 1.33609217]])

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [13]:
array_7 = np.random.rand(7, 7)

mean_arr = np.mean(array_7) # среднее
std_arr = np.std(array_7) # стандартное отклонение

print("Среднее:", mean_arr)
print("Стандартное отклонение:", std_arr)

normal_arr = (array_7 - mean_arr) / std_arr
print("Нормализованный массив:")
print(normal_arr)

Среднее: 0.5081660084723507
Стандартное отклонение: 0.2660111579710022
Нормализованный массив:
[[ 0.89218304 -1.53108991  1.0464349  -0.50698141 -0.96757047 -0.42190127
  -1.13857749]
 [-1.52951815  1.32189733 -0.33319615  0.76535922  0.56343704 -1.43672793
  -1.87495933]
 [ 0.07852012  0.19947713 -0.14523732 -0.32635939 -0.50045729  1.32524592
   1.06995869]
 [-1.49829665 -0.65003117  0.19120588 -1.15238103  0.71008371  0.04508556
  -0.23616865]
 [ 0.82058144  1.1339753   1.25152343  0.04346972  1.32022781  0.984675
   1.16986215]
 [-1.05528242 -0.3819762   1.75506289 -0.02377407 -1.36841249 -1.36571304
   0.99892172]
 [-1.57273869  1.55046392  0.99482566 -0.76039072  0.49472111 -0.22113609
   0.27167861]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
tips = sns.load_dataset("tips")

### Посмотрите на первые 5 строчек

In [ ]:
print(tips.head(5))

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
shape_rows = tips.shape[0] # Подсчет количества строк
shape_cols = tips.shape[1] # Подсчет количества столбцов

print("Количество строк:", shape_rows)
print("Количество столбцов:", shape_cols)

### Проверьте есть ли пропуски в данных

In [ ]:
el_nul = tips.isnull().sum()
print("Пропущенных значений в столбце:")
print(el_nul)

### Посмотрите на распределение числовых признаков

In [ ]:
tips.info()

In [ ]:
tips.describe()

### Найдите максимальное значение 'total_bill'

In [ ]:
max_total_bill = tips['total_bill'].max()
print("Max total_bill:", max_total_bill)

### Найдите количество курящих людей

In [ ]:
smokers = tips['smoker'].value_counts()['Yes']
print("Количество курящих людей:", smokers)

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
mean_of_day_total_billday = tips.groupby('day')['total_bill'].mean()
print("Mean total_bill of the day:")
print(mean_of_day_total_billday)

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
filtered_more_median_tips = tips[tips['total_bill'] > tips['total_bill'].median()]

mean_tip = filtered_more_median_tips.groupby('sex')['tip'].mean() # Cреднее 'tip' в зависимости от пола
print("Средний 'tip' в зависимости от пола:")
print(mean_tip)

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
smoker_n = {'Yes': 1, 'No': 0} # преобразование значений 'smoker' в бинарный формат
tips['smoker_bin'] = tips['smoker'].map(smoker_n)
print(tips[['smoker', 'smoker_bin']])

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
sns.histplot(tips['total_bill'], kde=True) # Гистограмма распределения признака 'total_bill'
plt.xlabel('total_bill')
plt.title('Total bill')
plt.show()

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
sns.scatterplot(data=tips, x='total_bill', y='tip') # Построение графика scatterplot
plt.xlabel('total_bill')
plt.ylabel('tip')
plt.title('Tip/Total Bill')
plt.show()

### Постройте pairplot

In [ ]:
sns.pairplot(tips) # Построение графика pairplot
plt.show()

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
sns.boxplot(data=tips, x='day', y='total_bill') # Построение графика boxplot
plt.xlabel('day')
plt.ylabel('total_bill')
plt.title('Total Bill/Day')
plt.show()

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
total_bill_time = tips.groupby('time')['total_bill'].count()
print(total_bill_time)

In [ ]:
sns.histplot(data=tips[tips['time'] == 'Dinner'], x='tip', color='yellow', label='Dinner')
sns.histplot(data=tips[tips['time'] == 'Lunch'], x='tip', color='green', label='Lunch')

plt.xlabel('tip')
plt.title('Histogram Tips of Time')
plt.legend()
plt.show()

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
sns.histplot(data=tips[tips['sex'] == 'Male'], x='tip', kde=True, color='blue', label='Male')
sns.histplot(data=tips[tips['sex'] == 'Female'], x='tip', kde=True, color='pink', label='Female')
plt.xlabel('tip')
plt.title('Histogram Tips of Male/Famele')
plt.legend()
plt.show()

In [ ]:
sum_sex = tips.groupby('sex')['smoker'].count()
print(sum_sex)

In [ ]:
sns.lmplot(x='size', y='total_bill', data=tips) # Гистограмма распределения признака 'total_bill' в зависимости от длительности посещения
plt.xlabel('total_bill')
plt.title('Total bill')
plt.show()

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# В датасете 244 наблюдения распределения суммы чека, в зависимости от признаков: размер чаевых; пола посетителя;
# признака, является посетитель курящим или нет; дня недели, посещения; времени посещения в течение дня;
# длительности посещения.
# Максимальный чек - 50,81. Средний чек в диапазоне - от 15 до 20, размер чаевых коррелирует с общим размером чека.
# Основная масса чаевых приходимтся на обеденное время. Среди посетителей больше чаевых оставляяют мужчины.
# 